[theme]
primaryColor = "#8b5cf6"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#141414"
textColor = "#ffffff"
font = "sans serif"

[client]
showSidebarNavigation = false

[browser]
gatherUsageStats = false
